analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6979346529114991
  lightness: 0.6022821012884378
  brandStrength: 0.3978495
  brandColors:
    - '#0E0F14'
    - '#5A88D0'
    - '#C6BEB3'
    - '#D8F0F3'
    - '#CD9154'
  rhythmicContrast: 0.9556681979447603
typography_spectrum: 0.7078853
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.969534
favicon: null
name: Speilet
